import Inner from "@/components/layout/Inner";
import PrimaryButton from "@/components/ui/PrimaryButton";
import Head from "next/head";
import Image from "next/image";
import { RevealAnimation } from "@/components/ui/RevealAnimation";
import Header from "@/components/ui/Header";
import Terminal from "@/components/ui/Terminal";

export default function Home() {
  const animationDelay: number = 0.7

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Inner>
        <div className="h-[100vh]">
          <div className="w-full justify-center flex">
            <Header text="IAN YEH" />
          </div>
          <RevealAnimation
            delay={animationDelay}
            className="grid grid-cols-1 md:grid-cols-2 gap-16 items-center mx-auto px-6"
          >
            {/* main component --> image, terminal emulator, something to draw attention */}
            <div className="h-[48vh]">
              {/*
              <Image
                src="/window.jpg"
                alt="Gradient Image"
                width={900}
                height={600}
                className="w-full h-[48vh] object-cover"
              />
              */}
              <Terminal />
            </div>

            {/* Text block */}
            <div className="h-full flex flex-col gap-6 items-center justify-end py-6 font-light">

              <p className="text-slate-900 text-md md:text-md w-[50%] mb-2">
                I&apos;m an 18 year old Software Engineer from Toronto, Canada. I care about building things for humans, by humans.
              </p>

              <div className="w-[50%] flex flex-row space-x-10">
                <PrimaryButton />
                <div className="h-full flex flex-col justify-center items-center mr-5">
                  <button className="" onClick={() => alert("hi")}>
                    <p className="text-sm font-normal">See my resume</p>
                  </button>
                </div>
              </div>
            </div>
          </RevealAnimation>

        </div>
      </Inner>
    </>
  );
}
