import Inner from "@/components/layout/Inner";
import PrimaryButton from "@/components/ui/PrimaryButton";
import Head from "next/head";
import Image from "next/image";
import { RevealAnimation } from "@/components/ui/RevealAnimation";
import Header from "@/components/ui/Header";

export default function Home() {
  const animationDelay: number = 0.7
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Inner>
        <div className="h-[100vh]">
          <Header text="IAN YEH" />
          <RevealAnimation 
            delay={animationDelay}
            className="grid grid-cols-2 gap-8 mt-8 px-4"
          >
            <div>
              <Image
                src={"/gradient.jpg"}
                alt="Gradient Image"
                width={500}
                height={300}
                className="w-full h-full object-cover rounded-4xl"
              />
            </div>
            <div className="flex flex-col gap-6 justify-end">
              <h2 className="text-xl md:text-3xl font-normal tracking-widest">
                I&apos;m a full-stack software engineer from Toronto, Canada.
              </h2>
              <p className="text-slate-600 font-light tracking-widest text-lg md:text-xl">
                I care about building things for humans, by humans.
              </p>
              <PrimaryButton />
            </div>
          </RevealAnimation>
        </div>
      </Inner>
    </>
  );
}
